version: "3.9"

services: 
  api:
    build: "./backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports: 
      - 8000:8000
  app:
    build: "./frontend"
    command: npm run serve
    volumes: 
      - ./frontend:/app
    ports: 
      - 8080:8080
    depends_on: 
      - api
