version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cooking_blog
      - POSTGRES_USER=kamil
      - POSTGRES_PASSWORD=test123 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build: "./backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports: 
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on: 
      - db
  app:
    build: "./frontend"
    command: npm run serve
    volumes: 
      - ./frontend:/app
    ports: 
      - 8080:8080
    depends_on: 
      - api

volumes:
  postgres_data: