# Generated by Django 3.0 on 2019-12-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191228_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
